
package com.zjpl.system.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MdmService", targetNamespace = "http://impl.service.mdm.neusoft.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MdmService {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.ResponseMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getData", targetNamespace = "http://impl.service.mdm.neusoft.com/", className = "com.zjpl.system.webservice.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://impl.service.mdm.neusoft.com/", className = "com.zjpl.system.webservice.GetDataResponse")
    public ResponseMessage getData(
        @WebParam(name = "arg0", targetNamespace = "")
        RequestMessage arg0);

}
