server:
  port: 8081
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    password: wymisgod
    database: 10
    # redis连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # redis连接池中的最小空闲连接
        min-idle: 0
        # redis连接池中的最大空闲连接
        max-idle: 8
        # redis连接池的最大数据库连接数
        max-active: 8
        # redis连接池最大阻塞等待时间（使用负值表示没有限制
        max-wait: -1s